from pydantic import BaseModel


def photo(photo_id: str) -> str:
    return f"https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1400&q=80"


class EventTemplate(BaseModel):
    slug: str
    title: str
    description: str
    categories: list[str]
    weekday: int
    start_hour: int
    start_minute: int
    end_hour: int
    end_minute: int
    venue: str
    address: str
    distance_km: float
    travel_minutes: int
    price: float
    rating: float
    image_url: str


EVENT_TEMPLATES: list[EventTemplate] = [
    EventTemplate(
        slug="ai-builders-workshop",
        title="AI Builders Workshop",
        description="A hands-on afternoon for people shipping small AI tools. You leave with a working prototype and a short critique from local builders.",
        categories=["technology", "workshops"],
        weekday=5,
        start_hour=14,
        start_minute=0,
        end_hour=16,
        end_minute=0,
        venue="Catalyst Hall",
        address="1840 N Halsted St, Chicago",
        distance_km=2.4,
        travel_minutes=12,
        price=20,
        rating=4.8,
        image_url=photo("photo-1531482615713-2afd69097998"),
    ),
    EventTemplate(
        slug="local-jazz-night",
        title="Local Jazz Night",
        description="A quartet plays two sets in a small room with good sightlines. The early set is unhurried and easy to pair with dinner later.",
        categories=["live_music"],
        weekday=5,
        start_hour=15,
        start_minute=0,
        end_hour=17,
        end_minute=0,
        venue="The Blue Lantern",
        address="2124 N Lincoln Ave, Chicago",
        distance_km=1.8,
        travel_minutes=10,
        price=15,
        rating=4.6,
        image_url=photo("photo-1415201364774-f6f0bb35f28f"),
    ),
    EventTemplate(
        slug="food-cocktail-festival",
        title="Food & Cocktail Festival",
        description="Neighborhood kitchens and bars share small plates and a few signature drinks in a park tent. You can wander in for an hour or stay the afternoon.",
        categories=["food"],
        weekday=5,
        start_hour=12,
        start_minute=0,
        end_hour=17,
        end_minute=0,
        venue="Oz Park",
        address="2021 N Burling St, Chicago",
        distance_km=3.6,
        travel_minutes=18,
        price=35,
        rating=4.5,
        image_url=photo("photo-1555939594-58d7cb561ad1"),
    ),
    EventTemplate(
        slug="cooking-class",
        title="Saturday Cooking Class",
        description="A chef walks a small group through a seasonal menu, then you eat what you made. The pace is practical, not performative.",
        categories=["food", "workshops"],
        weekday=5,
        start_hour=14,
        start_minute=0,
        end_hour=16,
        end_minute=30,
        venue="Hearth Studio",
        address="847 W Armitage Ave, Chicago",
        distance_km=3.1,
        travel_minutes=16,
        price=45,
        rating=4.7,
        image_url=photo("photo-1556910103-1c02745aae4d"),
    ),
    EventTemplate(
        slug="art-exhibition",
        title="New Work Exhibition",
        description="A quiet gallery afternoon with new painting and photography from Chicago artists. Easy to drop in without a ticketed tour.",
        categories=["arts"],
        weekday=5,
        start_hour=13,
        start_minute=0,
        end_hour=16,
        end_minute=0,
        venue="North Room Gallery",
        address="1950 N Damen Ave, Chicago",
        distance_km=1.4,
        travel_minutes=8,
        price=12,
        rating=4.2,
        image_url=photo("photo-1536924940846-227afb31e2a5"),
    ),
    EventTemplate(
        slug="startup-founder-meetup",
        title="Startup Founder Meetup",
        description="A morning circle for early-stage founders. Short intros, then time to compare what people are actually building.",
        categories=["technology"],
        weekday=5,
        start_hour=10,
        start_minute=0,
        end_hour=12,
        end_minute=0,
        venue="Workshop Annex",
        address="1000 W North Ave, Chicago",
        distance_km=2.8,
        travel_minutes=15,
        price=0,
        rating=4.4,
        image_url=photo("photo-1515187029135-18ee286d815b"),
    ),
    EventTemplate(
        slug="indie-film-screening",
        title="Indie Film Screening",
        description="A local short program followed by a conversation with one of the directors. Seats are reserved, and the room is small.",
        categories=["film"],
        weekday=5,
        start_hour=19,
        start_minute=0,
        end_hour=21,
        end_minute=0,
        venue="Lane Cinema",
        address="3309 N Clark St, Chicago",
        distance_km=2.6,
        travel_minutes=14,
        price=18,
        rating=4.3,
        image_url=photo("photo-1489599849927-2ee91cede3ba"),
    ),
    EventTemplate(
        slug="machine-learning-meetup",
        title="Machine Learning Meetup",
        description="Two short talks on applied models, then unstructured time. Friendly to people who build, not only people who research.",
        categories=["technology"],
        weekday=5,
        start_hour=18,
        start_minute=30,
        end_hour=20,
        end_minute=30,
        venue="Signal Club",
        address="1550 N Milwaukee Ave, Chicago",
        distance_km=2.1,
        travel_minutes=11,
        price=0,
        rating=4.6,
        image_url=photo("photo-1677442136019-21780ecad995"),
    ),
    EventTemplate(
        slug="photography-walk",
        title="Photography Walk",
        description="A slow walk with a local photographer and a few prompts. You need a camera or a phone and shoes you can stand in.",
        categories=["outdoors"],
        weekday=5,
        start_hour=13,
        start_minute=0,
        end_hour=15,
        end_minute=0,
        venue="Lincoln Park Conservatory",
        address="2391 N Stockton Dr, Chicago",
        distance_km=5.2,
        travel_minutes=25,
        price=10,
        rating=4.1,
        image_url=photo("photo-1452587925148-ce544e77e70d"),
    ),
    EventTemplate(
        slug="live-comedy-show",
        title="Live Comedy Show",
        description="A late lineup of local comics in a basement room. The show runs long and the neighborhood is a trek from home.",
        categories=["comedy"],
        weekday=5,
        start_hour=20,
        start_minute=0,
        end_hour=21,
        end_minute=30,
        venue="Lower Room",
        address="1360 N Milwaukee Ave, Chicago",
        distance_km=7.4,
        travel_minutes=35,
        price=25,
        rating=4.4,
        image_url=photo("photo-1527224857830-43a7acc85260"),
    ),
    EventTemplate(
        slug="design-sprint-social",
        title="Design Sprint Social",
        description="An afternoon working session with a ticket price aimed at company offsites. Interesting if budget is not the point.",
        categories=["technology", "workshops"],
        weekday=5,
        start_hour=14,
        start_minute=0,
        end_hour=16,
        end_minute=0,
        venue="Atelier West",
        address="1650 W Hubbard St, Chicago",
        distance_km=2.5,
        travel_minutes=13,
        price=80,
        rating=4.0,
        image_url=photo("photo-1529156069898-49953e39b3ac"),
    ),
    EventTemplate(
        slug="symphony-gala",
        title="Symphony Gala",
        description="A formal evening concert with a reception. The ticket and the trip both sit well outside a casual afternoon.",
        categories=["live_music"],
        weekday=5,
        start_hour=19,
        start_minute=0,
        end_hour=22,
        end_minute=0,
        venue="Civic Music Hall",
        address="220 S Michigan Ave, Chicago",
        distance_km=9.5,
        travel_minutes=40,
        price=140,
        rating=4.8,
        image_url=photo("photo-1465847899084-d164df4dedc6"),
    ),
    EventTemplate(
        slug="sunday-market",
        title="Sunday Makers Market",
        description="Food stalls, a short acoustic set, and a craft row. A lighter way to spend a late Sunday morning.",
        categories=["food", "live_music"],
        weekday=6,
        start_hour=11,
        start_minute=0,
        end_hour=14,
        end_minute=0,
        venue="Armitage Market",
        address="1000 W Armitage Ave, Chicago",
        distance_km=1.6,
        travel_minutes=9,
        price=15,
        rating=4.3,
        image_url=photo("photo-1488459716781-31db52582fe9"),
    ),
    EventTemplate(
        slug="evening-jazz-room",
        title="Evening Jazz Room",
        description="A seated early-evening quartet in a small room. The set is built to follow dinner and still end before a late night.",
        categories=["live_music"],
        weekday=5,
        start_hour=20,
        start_minute=0,
        end_hour=21,
        end_minute=30,
        venue="Halsted Listening Room",
        address="1954 N Halsted St, Chicago",
        distance_km=2.0,
        travel_minutes=12,
        price=32,
        rating=4.7,
        image_url=photo("photo-1415201364774-f6f0bb35f28f"),
    ),
    EventTemplate(
        slug="friday-listening-room",
        title="Friday Listening Room",
        description="A seated early-evening set of new local songs. Built for people who want music before the night gets loud.",
        categories=["live_music"],
        weekday=4,
        start_hour=18,
        start_minute=0,
        end_hour=19,
        end_minute=30,
        venue="The Blue Lantern",
        address="2124 N Lincoln Ave, Chicago",
        distance_km=1.8,
        travel_minutes=10,
        price=20,
        rating=4.5,
        image_url=photo("photo-1511671782779-c97d3d27a1d4"),
    ),
]
