from pydantic import BaseModel

from app.integrations.events.catalog import photo


class RestaurantTemplate(BaseModel):
    slug: str
    name: str
    description: str
    cuisines: list[str]
    address: str
    distance_km: float
    travel_minutes: int
    price_level: int
    typical_price: float
    rating: float
    image_url: str


RESTAURANT_TEMPLATES: list[RestaurantTemplate] = [
    RestaurantTemplate(
        slug="kura",
        name="Kura",
        description="A neighborhood sushi counter with a tight evening menu and a calm room. The cooked dishes are as considered as the nigiri.",
        cuisines=["japanese"],
        address="1954 N Halsted St, Chicago",
        distance_km=2.1,
        travel_minutes=11,
        price_level=2,
        typical_price=48,
        rating=4.7,
        image_url=photo("photo-1579871494447-9811cf80d66c"),
    ),
    RestaurantTemplate(
        slug="nori-ramen",
        name="Nori Ramen House",
        description="A focused ramen shop with a rich shoyu bowl and a short list of small plates. Easy to get in and out on a weeknight.",
        cuisines=["japanese"],
        address="2460 N Lincoln Ave, Chicago",
        distance_km=1.5,
        travel_minutes=8,
        price_level=1,
        typical_price=22,
        rating=4.5,
        image_url=photo("photo-1569718212165-3a8278d5f624"),
    ),
    RestaurantTemplate(
        slug="yoru-izakaya",
        name="Yoru Izakaya",
        description="Skewers, a few raw dishes, and a room that works for one person or a small group. The kitchen is open through a normal dinner hour.",
        cuisines=["japanese"],
        address="1369 N Milwaukee Ave, Chicago",
        distance_km=2.8,
        travel_minutes=14,
        price_level=2,
        typical_price=46,
        rating=4.6,
        image_url=photo("photo-1553621042-f6e147245754"),
    ),
    RestaurantTemplate(
        slug="sora-handroll",
        name="Sora Handroll",
        description="Hand rolls made to order, with a menu that stays under a casual dinner budget. The counter turns over quickly.",
        cuisines=["japanese"],
        address="1959 W Chicago Ave, Chicago",
        distance_km=3.4,
        travel_minutes=18,
        price_level=2,
        typical_price=36,
        rating=4.4,
        image_url=photo("photo-1617196034796-73dfa7b1fd56"),
    ),
    RestaurantTemplate(
        slug="luca-trattoria",
        name="Luca Trattoria",
        description="A pasta-forward Italian room with a neighborhood pace. Good when the plan is dinner rather than a special occasion.",
        cuisines=["italian"],
        address="2530 N Milwaukee Ave, Chicago",
        distance_km=2.3,
        travel_minutes=12,
        price_level=2,
        typical_price=52,
        rating=4.6,
        image_url=photo("photo-1498579150354-977475b7ea0b"),
    ),
    RestaurantTemplate(
        slug="siam-room",
        name="Siam Room",
        description="A reliable Thai menu with enough range for a weeknight. The curries are the reason regulars come back.",
        cuisines=["thai"],
        address="2210 N Sheffield Ave, Chicago",
        distance_km=1.7,
        travel_minutes=9,
        price_level=1,
        typical_price=28,
        rating=4.4,
        image_url=photo("photo-1559314809-0d155014e29e"),
    ),
    RestaurantTemplate(
        slug="saffron-house",
        name="Saffron House",
        description="Northern Indian plates and a tandoor that is worth the trip. Portions make it easy to share.",
        cuisines=["indian"],
        address="1635 W Division St, Chicago",
        distance_km=3.0,
        travel_minutes=15,
        price_level=2,
        typical_price=32,
        rating=4.5,
        image_url=photo("photo-1585937421612-70a008356fbe"),
    ),
    RestaurantTemplate(
        slug="han-river",
        name="Han River BBQ",
        description="Tabletop Korean barbecue with banchan that shows up quickly. Better with more than one person.",
        cuisines=["korean"],
        address="2535 N Lincoln Ave, Chicago",
        distance_km=4.0,
        travel_minutes=20,
        price_level=2,
        typical_price=40,
        rating=4.3,
        image_url=photo("photo-1498654896293-37aacf113fd9"),
    ),
    RestaurantTemplate(
        slug="calle-rosa",
        name="Calle Rosa",
        description="A compact Mexican spot for tacos and a couple of larger plates. The salsa bar is the quiet highlight.",
        cuisines=["mexican"],
        address="2100 N Milwaukee Ave, Chicago",
        distance_km=2.5,
        travel_minutes=13,
        price_level=1,
        typical_price=26,
        rating=4.4,
        image_url=photo("photo-1565299585323-38d6b0865b47"),
    ),
    RestaurantTemplate(
        slug="north-and-main",
        name="North & Main",
        description="A seasonal Canadian-leaning menu: smoked fish, prairie grains, and a short wine list. It feels like a proper dinner without being formal.",
        cuisines=["canadian"],
        address="2201 N Clybourn Ave, Chicago",
        distance_km=3.2,
        travel_minutes=16,
        price_level=2,
        typical_price=44,
        rating=4.2,
        image_url=photo("photo-1467003909585-2f8a72700288"),
    ),
    RestaurantTemplate(
        slug="marlowe",
        name="Marlowe",
        description="A cocktail bar with a real food menu, not just snacks. Useful when the plan is a drink and something to eat.",
        cuisines=["cocktail_bar"],
        address="2438 N Lincoln Ave, Chicago",
        distance_km=1.9,
        travel_minutes=10,
        price_level=2,
        typical_price=38,
        rating=4.6,
        image_url=photo("photo-1470337458703-46ad1756a187"),
    ),
    RestaurantTemplate(
        slug="paper-and-rye",
        name="Paper & Rye",
        description="A daytime cafe that also does a simple early dinner. Best if the meal should stay light.",
        cuisines=["cafe"],
        address="1850 N Milwaukee Ave, Chicago",
        distance_km=1.1,
        travel_minutes=6,
        price_level=1,
        typical_price=18,
        rating=4.3,
        image_url=photo("photo-1495474472287-4d71bcdd2085"),
    ),
    RestaurantTemplate(
        slug="ginza-private",
        name="Ginza Private Room",
        description="An omakase counter with a fixed high price. Excellent, and well outside a casual budget.",
        cuisines=["japanese"],
        address="60 W Kinzie St, Chicago",
        distance_km=3.0,
        travel_minutes=15,
        price_level=4,
        typical_price=160,
        rating=4.9,
        image_url=photo("photo-1553621042-f6e147245754"),
    ),
    RestaurantTemplate(
        slug="hokkaido-grill",
        name="Hokkaido Grill",
        description="A strong Japanese grill on the far side of the city. Worth it when travel time does not matter.",
        cuisines=["japanese"],
        address="6230 N Broadway, Chicago",
        distance_km=11.2,
        travel_minutes=42,
        price_level=2,
        typical_price=55,
        rating=4.5,
        image_url=photo("photo-1579871494447-9811cf80d66c"),
    ),
]
