"""initial schema

Revision ID: ad1a206d0e8d
Revises:
Create Date: 2026-10-02 14:21:16.454254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ad1a206d0e8d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "interaction_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.String(length=160), nullable=True),
        sa.Column("event_name", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_interaction_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_events")),
    )
    op.create_index(
        op.f("ix_interaction_events_session_id"), "interaction_events", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_interaction_events_user_id"), "interaction_events", ["user_id"], unique=False
    )
    op.create_table(
        "planning_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("user_request", sa.Text(), nullable=False),
        sa.Column("follow_up", sa.Text(), nullable=True),
        sa.Column("plan_type", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("clarification_question", sa.Text(), nullable=True),
        sa.Column("selected_candidate_id", sa.String(length=160), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_planning_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planning_sessions")),
    )
    op.create_index(
        op.f("ix_planning_sessions_created_at"), "planning_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_planning_sessions_status"), "planning_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_planning_sessions_user_id"), "planning_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_event_categories", sa.JSON(), nullable=False),
        sa.Column("preferred_cuisines", sa.JSON(), nullable=False),
        sa.Column("disliked_categories", sa.JSON(), nullable=False),
        sa.Column("default_budget", sa.Float(), nullable=True),
        sa.Column("max_travel_minutes", sa.Integer(), nullable=True),
        sa.Column("preferred_days", sa.JSON(), nullable=False),
        sa.Column("preferred_time_ranges", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_preferences_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_preferences_user_id")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["planning_sessions.id"],
            name=op.f("fk_agent_runs_session_id_planning_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_runs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_session_id"), "agent_runs", ["session_id"], unique=False)
    op.create_table(
        "local_calendar_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("planning_session_id", sa.Uuid(), nullable=True),
        sa.Column("seed_key", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["planning_session_id"],
            ["planning_sessions.id"],
            name=op.f("fk_local_calendar_events_planning_session_id_planning_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_local_calendar_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local_calendar_events")),
        sa.UniqueConstraint("seed_key", name=op.f("uq_local_calendar_events_seed_key")),
    )
    op.create_index(
        op.f("ix_local_calendar_events_start_at"),
        "local_calendar_events",
        ["start_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_local_calendar_events_user_id"), "local_calendar_events", ["user_id"], unique=False
    )
    op.create_table(
        "planning_constraints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["planning_sessions.id"],
            name=op.f("fk_planning_constraints_session_id_planning_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planning_constraints")),
        sa.UniqueConstraint("session_id", name=op.f("uq_planning_constraints_session_id")),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["planning_sessions.id"],
            name=op.f("fk_recommendations_session_id_planning_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_recommendations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(
        op.f("ix_recommendations_session_id"), "recommendations", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False
    )
    op.create_table(
        "agent_run_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_run_events_agent_run_id_agent_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_run_events")),
    )
    op.create_index(
        op.f("ix_agent_run_events_agent_run_id"), "agent_run_events", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_run_events_session_id"), "agent_run_events", ["session_id"], unique=False
    )
    op.create_table(
        "calendar_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.String(length=160), nullable=False),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("local_calendar_event_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["local_calendar_event_id"],
            ["local_calendar_events.id"],
            name=op.f("fk_calendar_actions_local_calendar_event_id_local_calendar_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["planning_sessions.id"],
            name=op.f("fk_calendar_actions_session_id_planning_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_calendar_actions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_actions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_calendar_actions_idempotency_key")),
    )
    op.create_index(
        op.f("ix_calendar_actions_session_id"), "calendar_actions", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_actions_user_id"), "calendar_actions", ["user_id"], unique=False
    )
    op.create_table(
        "recommendation_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.String(length=160), nullable=False),
        sa.Column("candidate_type", sa.String(length=32), nullable=False),
        sa.Column("rank_position", sa.Integer(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("preference_score", sa.Float(), nullable=False),
        sa.Column("schedule_score", sa.Float(), nullable=False),
        sa.Column("distance_score", sa.Float(), nullable=False),
        sa.Column("price_score", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("scheduled", sa.Boolean(), nullable=False),
        sa.Column("rejected", sa.Boolean(), nullable=False),
        sa.Column("shown", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=40), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_recommendation_candidates_recommendation_id_recommendations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_candidates")),
    )
    op.create_index(
        op.f("ix_recommendation_candidates_recommendation_id"),
        "recommendation_candidates",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_candidates_session_id"),
        "recommendation_candidates",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_candidates_user_id"),
        "recommendation_candidates",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recommendation_candidates_user_id"), table_name="recommendation_candidates"
    )
    op.drop_index(
        op.f("ix_recommendation_candidates_session_id"), table_name="recommendation_candidates"
    )
    op.drop_index(
        op.f("ix_recommendation_candidates_recommendation_id"),
        table_name="recommendation_candidates",
    )
    op.drop_table("recommendation_candidates")
    op.drop_index(op.f("ix_calendar_actions_user_id"), table_name="calendar_actions")
    op.drop_index(op.f("ix_calendar_actions_session_id"), table_name="calendar_actions")
    op.drop_table("calendar_actions")
    op.drop_index(op.f("ix_agent_run_events_session_id"), table_name="agent_run_events")
    op.drop_index(op.f("ix_agent_run_events_agent_run_id"), table_name="agent_run_events")
    op.drop_table("agent_run_events")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_session_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_table("planning_constraints")
    op.drop_index(op.f("ix_local_calendar_events_user_id"), table_name="local_calendar_events")
    op.drop_index(op.f("ix_local_calendar_events_start_at"), table_name="local_calendar_events")
    op.drop_table("local_calendar_events")
    op.drop_index(op.f("ix_agent_runs_session_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_planning_sessions_user_id"), table_name="planning_sessions")
    op.drop_index(op.f("ix_planning_sessions_status"), table_name="planning_sessions")
    op.drop_index(op.f("ix_planning_sessions_created_at"), table_name="planning_sessions")
    op.drop_table("planning_sessions")
    op.drop_index(op.f("ix_interaction_events_user_id"), table_name="interaction_events")
    op.drop_index(op.f("ix_interaction_events_session_id"), table_name="interaction_events")
    op.drop_table("interaction_events")
    op.drop_table("users")
    # ### end Alembic commands ###
